baseURL = "https://www.schneidertorpet.com/"
languageCode = "en-us"
title = "Schneidertorpet"
theme = "researcher"
enableEmoji = true
publishDir = "docs"

[params]
  author = "Schneiders"
  description = "det Schneiderska torpet."
  favicon = "torpet2.ico"  # path to a .ico to use as favicon
  [params.footer]
    text = "By Schneiders"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "Om torpet"
    url = "/about"
    weight = 2
  [[menu.main]]
    name = "Evenemang"
    url = "/events"
    weight = 3


[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
